baseURL = "https://luh-dbsreadinggroup.github.io"
title = "LUH DBS Reading Group"
description = "Leibniz University Hannover Data Systems Paper Reading Group"

languageCode = "en"
languageName = "English"

[modules]
[[module.imports]]
path = "github.com/dillonzq/LoveIt"
ref = "v0.3.0"

[menu]

[[menu.main]]
weight = 2
identifier = "Papers"
name = "Papers"
url = "/papers/"
title = "Reading group papers"

[[menu.main]]
weight = 1
identifier = "About"
name = "About"
url = "/about/"
title = "About the group"

[params]
defaultTheme = "auto"
title = "LUH DBS Reading Group"
description = "Student-organized weekly paper reading group for data systems at Leibniz University Hannover, Germany." 
  
[params.header]
desktopMode = "fixed"
mobileMode = "auto"

[params.header.title]
name = "LUH DBS Paper Reading Group"
pre = "<i class='fas fa-database fa-fw' aria-hidden='true'></i>"

[params.author]
name = "LUH DBS Reading Group"

[params.footer]
enable = true
hugo = false
copyright = true
author = true
since = 2025

[params.social]
Github = "luh-dbsreadinggroup"

[params.home.profile]
enable = true
title = "LUH DBS Paper Reading Group"
subtitle = "Leibniz University Hannover Data Systems Paper Reading Group"
avatarUrl = "/images/dbs_rev2.png"

[params.home.posts]
enable = false
  
[markup]
[markup.highlight]
noClasses = false

